import type { BootstrapData, LayerId, Organization } from './types'
import { DEMO_CATEGORIES } from './cosmosModel'

// All names, needs, observation events and contribution records below are FICTIONAL.
// The actual base-map imagery is external satellite imagery, not this fixture data.
const updatedAt = '2026-10-02T17:30:00Z'

function organization(
  id: string,
  name: string,
  location: string,
  coordinates: [number, number],
  situation: string,
  item: string,
  quantity: number,
  fulfilled: number,
  unit: string,
  urgency: 'urgent' | 'standard',
  category?: LayerId,
  type = 'Community relief organization',
): Organization {
  return {
    id,
    name,
    category,
    type,
    location,
    coordinates,
    situation,
    description:
      'A fictional, locally led organization supporting its neighbours. Created for the AidAtlas demo.',
    links: {},
    updatedAt,
    sample: true,
    volunteerRole: 'Community supply packing',
    volunteerSlots: 8,
    requests: [
      {
        id: `${id}-request-1`,
        organizationId: id,
        impactCategory: category ?? DEMO_CATEGORIES[id],
        title: `${item} for local families`,
        item,
        quantity,
        fulfilled,
        unit,
        urgency,
        description:
          'New, unopened supplies are needed. The team will confirm collection arrangements after reviewing your pledge.',
        status: 'published',
        confirmedAt: updatedAt,
        createdAt: updatedAt,
        updatedAt,
        links: {},
      },
    ],
  }
}

export const demoData: BootstrapData = {
  session: { id: 'demo-supporter', name: 'Alex Morgan', role: 'supporter', demo: true },
  organizations: [
    organization(
      'okanagan',
      'Okanagan Community Relief',
      'Kelowna, British Columbia',
      [-119.496, 49.888],
      'Our community hub is preparing essential supplies for families displaced by nearby wildfire activity. Local volunteers are coordinating distribution.',
      'Emergency supply kits',
      120,
      46,
      'kits',
      'urgent',
      'wildfire',
    ),
    organization(
      'coast',
      'Coast Community Kitchen',
      'Vancouver, British Columbia',
      [-123.121, 49.283],
      'Our kitchen prepares warm meals for neighbours facing food insecurity. Pantry supplies help keep the kitchen open throughout the week.',
      'Pantry food boxes',
      200,
      138,
      'boxes',
      'standard',
    ),
    organization(
      'guatemala',
      'Highland Care Collective',
      'Antigua, Guatemala',
      [-90.734, 14.558],
      'Community teams are delivering clean water to villages after heavy rainfall affected local roads and water supplies.',
      'Water filter kits',
      80,
      25,
      'kits',
      'standard',
      'flood',
    ),
    organization(
      'morocco',
      'Atlas Neighbour Network',
      'Marrakesh, Morocco',
      [-7.982, 31.63],
      'We support rural communities with essential household supplies and help families prepare for colder nights.',
      'Warm blankets',
      160,
      89,
      'blankets',
      'standard',
    ),
    organization(
      'kenya',
      'Tana River Community Hub',
      'Garissa, Kenya',
      [39.646, -0.453],
      'Local coordinators are restocking water and hygiene supplies for households affected by seasonal flooding.',
      'Hygiene packs',
      100,
      32,
      'packs',
      'standard',
      'flood',
    ),
    organization(
      'nepal',
      'Valley Together',
      'Kathmandu, Nepal',
      [85.324, 27.717],
      'Neighbourhood volunteers are assembling school supplies for children returning to class after local disruptions.',
      'School supply packs',
      90,
      57,
      'packs',
      'standard',
      'education',
    ),
    organization(
      'philippines',
      'Bayanihan Coastal Care',
      'Tacloban, Philippines',
      [125.005, 11.243],
      'Our coastal community is preparing emergency supplies and supporting households with limited access to clean drinking water.',
      'Drinking water cases',
      140,
      38,
      'cases',
      'standard',
      'storm',
    ),
    organization(
      'korea',
      'Han River Neighbours',
      'Seoul, South Korea',
      [126.978, 37.566],
      'Our volunteer team checks in on older neighbours during periods of extreme heat and delivers everyday essentials.',
      'Cooling care kits',
      70,
      41,
      'kits',
      'standard',
    ),
    // More fictional organizations so every Explore layer has a few to show. A sample need is
    // urgent only where real data shows a disaster nearby: Okanagan (the BC 2023 fire replay),
    // Kharkiv (recorded conflict events), Muzaffarpur (flood) and Guaymas (storm).
    organization(
      'shuswap',
      'North Shuswap Community Hall',
      'Scotch Creek, British Columbia',
      [-119.455, 50.915],
      'The hall became a gathering point for families after nearby wildfires. Volunteers are sorting donated food and supplies.',
      'Non-perishable food hampers',
      50,
      18,
      'hampers',
      'standard',
      'wildfire',
      'Community centre',
    ),
    organization(
      'evia',
      'Evia Fire Recovery Network',
      'Istiaia, Greece',
      [23.15, 38.95],
      'Neighbours are helping families whose homes and olive groves were damaged by summer wildfires.',
      'Respirator masks',
      300,
      120,
      'masks',
      'standard',
      'wildfire',
    ),
    organization(
      'sylhet',
      'Sylhet Flood Response',
      'Sylhet, Bangladesh',
      [91.87, 24.89],
      'Volunteer boat teams are reaching villages cut off by monsoon flooding with clean water supplies.',
      'Water purification tablets',
      5000,
      1800,
      'tablets',
      'standard',
      'flood',
    ),
    organization(
      'kingston',
      'Island Storm Recovery',
      'Kingston, Jamaica',
      [-76.79, 18.0],
      'After the hurricane season, our crews are helping families make damaged roofs watertight again.',
      'Roof tarps',
      200,
      64,
      'tarps',
      'standard',
      'storm',
    ),
    organization(
      'manaus',
      'Amazon Canopy Keepers',
      'Manaus, Brazil',
      [-60.02, -3.12],
      'Community nurseries are growing native trees to replant cleared land along the river.',
      'Native tree seedlings',
      2000,
      740,
      'seedlings',
      'standard',
      'nature',
      'Nature restoration group',
    ),
    organization(
      'cairns',
      'Reef Restoration Collective',
      'Cairns, Australia',
      [145.77, -16.92],
      'Volunteer divers are rebuilding coral nurseries on reefs damaged by marine heatwaves.',
      'Coral nursery frames',
      60,
      22,
      'frames',
      'standard',
      'nature',
      'Nature restoration group',
    ),
    organization(
      'kharkiv',
      'Kharkiv Civilian Aid Network',
      'Kharkiv, Ukraine',
      [36.23, 49.99],
      'Volunteers deliver heating and food to older residents and displaced families through the winter.',
      'Winter heating kits',
      400,
      150,
      'kits',
      'urgent',
      'conflict',
      'Civilian relief organization',
    ),
    organization(
      'port-sudan',
      'Red Sea Displacement Relief',
      'Port Sudan, Sudan',
      [37.22, 19.62],
      'Our teams support families who fled the fighting and now live in temporary shelters in the city.',
      'Family food parcels',
      500,
      130,
      'parcels',
      'standard',
      'conflict',
      'Civilian relief organization',
    ),
    organization(
      'lagos',
      'Lagos Learning Circles',
      'Lagos, Nigeria',
      [3.38, 6.52],
      'Evening study circles help children who left school catch up on reading and maths.',
      'Solar study lamps',
      250,
      90,
      'lamps',
      'standard',
      'education',
      "Children's education charity",
    ),
    // Placed inside real current disaster areas (GDACS) for the demo, as if each had accepted the
    // check-in and confirmed an urgent need: the Bihar flood area and POLO-26's 120 km/h wind zone.
    organization(
      'muzaffarpur',
      'Bihar Flood Relief Collective',
      'Muzaffarpur, India',
      [85.39, 26.12],
      'Volunteer boat teams are bringing drinking water and dry rations to families cut off by river flooding. The team confirmed this need after the satellite check-in.',
      'Drinking water kits',
      400,
      90,
      'kits',
      'urgent',
      'flood',
    ),
    organization(
      'guaymas',
      'Sonora Coast Storm Relief',
      'Guaymas, Mexico',
      [-110.9, 27.92],
      'Hurricane winds damaged roofs and power lines along the coast. Our crews confirmed this need after the storm check-in.',
      'Roof tarps and repair kits',
      250,
      40,
      'kits',
      'urgent',
      'storm',
      'Community centre',
    ),
    // Domestic-violence services are shown at city level only. Shelter locations are never mapped.
    organization(
      'toronto-safety',
      'Safe Harbour Support Line',
      'Toronto, Ontario',
      [-79.38, 43.65],
      'A confidential support line and advocacy service for people leaving abusive relationships. Location shown at city level only.',
      'Prepaid phones for survivors',
      80,
      31,
      'phones',
      'standard',
      'domestic_violence',
      'Support service',
    ),
    organization(
      'london-safety',
      'Open Door Advocacy',
      'London, United Kingdom',
      [-0.12, 51.51],
      'Advocates help survivors with safety planning, legal support and safe travel. Location shown at city level only.',
      'Emergency travel vouchers',
      120,
      40,
      'vouchers',
      'standard',
      'domestic_violence',
      'Support service',
    ),
  ],
  observations: [
    {
      id: 'observation-okanagan-1',
      organizationId: 'okanagan',
      title: 'Elevated thermal activity',
      summary:
        'A simulated satellite detection indicates elevated thermal activity nearby. Satellite observations alone do not establish local impact or a need for assistance.',
      coordinates: [-119.59, 49.91],
      source: 'NASA FIRMS / VIIRS · simulated detection',
      observedAt: '2026-10-02T16:40:00Z',
      proximityKm: 7.2,
      simulated: true,
      playback: false,
      detectionCount: 3,
      draftSource: 'template',
      question: 'New satellite observations near your organization. Are you affected?',
      suggestedItems: [{ item: 'Emergency supply kits', quantity: 50, unit: 'kits' }],
    },
  ],
  contributions: [
    {
      id: 'sample-contribution-1',
      organizationId: 'coast',
      organizationName: 'Coast Community Kitchen',
      kind: 'supplies',
      summary: '12 pantry food boxes',
      quantity: 12,
      createdAt: '2026-09-12T14:00:00Z',
      status: 'organization_confirmed',
      confirmedQuantity: 12,
      confirmedAt: '2026-09-13T12:00:00Z',
      simulated: true,
    },
    {
      id: 'sample-contribution-2',
      organizationId: 'nepal',
      organizationName: 'Valley Together',
      kind: 'donate',
      summary: '$25 USD contribution',
      quantity: 25,
      createdAt: '2026-09-21T10:30:00Z',
      status: 'organization_confirmed',
      confirmedQuantity: 25,
      confirmedAt: '2026-09-22T12:00:00Z',
      simulated: true,
    },
    {
      id: 'sample-contribution-3',
      organizationId: 'okanagan',
      organizationName: 'Okanagan Community Relief',
      kind: 'volunteer',
      summary: '2 hours of volunteer time',
      quantity: 2,
      createdAt: '2026-10-01T19:00:00Z',
      status: 'pledged',
      simulated: true,
    },
  ],
}
